services:
  # INFRASCTRUCTURE - MONITORING
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
    networks:
      - company-network
      - monitoring-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
  grafana:
    image: grafana/grafana:9.5.2
    
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana.yml:/etc/grafana/grafana.yml
    depends_on:
      - prometheus
    networks:
      - monitoring-network  

  # INFRASCTRUCTURE - DATABASE
  company-postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - company-network
    environment:
      - POSTGRES_DB=${COMPANY_POSTGRES_DB}
      - POSTGRES_USER=${COMPANY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${COMPANY_POSTGRES_PASSWORD}


  # INFRASCTRUCTURE - MICROSERVICES
  company-service:
    build:
      context: ./company-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - COMPANY_SPRING_DATASOURCE_URL=${COMPANY_SPRING_DATASOURCE_URL}
      - COMPANY_POSTGRES_USER=${COMPANY_POSTGRES_USER}
      - COMPANY_POSTGRES_PASSWORD=${COMPANY_POSTGRES_PASSWORD}

      - COMPANY_REDIS_CACHE_PASSWORD=${COMPANY_REDIS_CACHE_PASSWORD}
      - COMPANY_REDIS_CACHE_PORT=${COMPANY_REDIS_CACHE_PORT}
      - COMPANY_REDIS_CACHE_URL=${COMPANY_REDIS_CACHE_URL}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true

      - EUREKA_URL_DEFAULT=${EUREKA_URL_DEFAULT}
    depends_on:
      - company-postgres
      - discovery-service
    networks:
      - company-network
    volumes:
      - .env:/app/.env


networks:
  company-network:
  monitoring-network:

volumes:
  postgres_data: