services:
  # LOADBALANCER - NGINX
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - company-network 
      - order-network
      - monitoring-network
      - gateway-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  # GATEWAY
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE}
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
      - KONG_PROXY_LISTEN=0.0.0.0:8000
    volumes:
      - ./kong.yaml:/usr/local/kong/declarative/kong.yaml
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - gateway-network
      - company-network
      - order-network
      - monitoring-network
    depends_on:
      - kong-migration
    healthcheck:
      test: ["CMD", "kong", "health"]
      interval: 10s
      timeout: 10s
      retries: 10

  # INFRASCTRUCTURE - MONITORING
  discovery-service:
    build:
      context: ./discovery-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8761:8761"
    environment:
      - EUREKA_HOSTNAME=${EUREKA_HOSTNAME}
    networks:
      - company-network
      - order-network
      - monitoring-network
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring-network
  grafana:
    image: grafana/grafana:9.5.2
    
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ./grafana.yml:/etc/grafana/grafana.yml
    depends_on:
      - prometheus
    networks:
      - monitoring-network  

  # INFRASCTRUCTURE - DATABASE
  kong-database:
    image: postgres:latest
    container_name: kong-database
    environment:
      - POSTGRES_DB=${KONG_POSTGRES_DB}
      - POSTGRES_USER=${KONG_POSTGRES_USER}
      - POSTGRES_PASSWORD=${KONG_POSTGRES_PASSWORD}
    ports:
      - "5440:5432"
    networks:
      - gateway-network
    volumes:
      - kong_postgres_data:/var/lib/postgresql/data
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "admin", "-d", "kong_db"]
        interval: 5s
        timeout: 5s
        retries: 5
  company-postgres:
    container_name: company-postgres
    image: postgres:latest
    ports:
      - "5434:5432"
    volumes:
      - company_postgres_data:/var/lib/postgresql/data
    networks:
      - company-network
    environment:
      - POSTGRES_DB=${COMPANY_POSTGRES_DB}
      - POSTGRES_USER=${COMPANY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${COMPANY_POSTGRES_PASSWORD}
  order-postgres:
    container_name: order-postgres
    image: postgres:latest
    ports:
      - "5435:5432"
    volumes:
      - order_postgres_data:/var/lib/postgresql/data
    networks:
      - order-network
    environment:
      - POSTGRES_DB=${ORDER_POSTGRES_DB}
      - POSTGRES_USER=${ORDER_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDER_POSTGRES_PASSWORD}
        
  ## MIGRATION
  kong-migration:
    image: kong:latest
    command: kong migrations bootstrap
    environment:
      - KONG_DATABASE=${KONG_DATABASE}
      - KONG_PG_HOST=${KONG_PG_HOST}
      - KONG_PG_USER=${KONG_PG_USER}
      - KONG_PG_PASSWORD=${KONG_PG_PASSWORD}
      - KONG_PG_DATABASE=${KONG_PG_DATABASE}

    networks:
      - gateway-network
    depends_on:
      kong-database:
        condition: service_healthy
    restart: on-failure  

  # INFRASCTRUCTURE - MICROSERVICES
  company-service:
    container_name: company-service-1
    build:
      context: ./company-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - COMPANY_SPRING_DATASOURCE_URL=${COMPANY_SPRING_DATASOURCE_URL}
      - COMPANY_POSTGRES_USER=${COMPANY_POSTGRES_USER}
      - COMPANY_POSTGRES_PASSWORD=${COMPANY_POSTGRES_PASSWORD}

      - REDIS_CACHE_PASSWORD=${REDIS_CACHE_PASSWORD}
      - REDIS_CACHE_PORT=${REDIS_CACHE_PORT}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true

      - EUREKA_URL_DEFAULT=${EUREKA_URL_DEFAULT}
    depends_on:
      - company-postgres
      - discovery-service
    networks:
      - company-network
    volumes:
      - .env:/app/.env
  order-service:
    container_name: order-service-1
    build:
      context: ./order-service
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8081:8080"
    environment:
      - ORDER_SPRING_DATASOURCE_URL=${ORDER_SPRING_DATASOURCE_URL}
      - ORDER_POSTGRES_USER=${ORDER_POSTGRES_USER}
      - ORDER_POSTGRES_PASSWORD=${ORDER_POSTGRES_PASSWORD}

      - REDIS_CACHE_PASSWORD=${REDIS_CACHE_PASSWORD}
      - REDIS_CACHE_PORT=${REDIS_CACHE_PORT}
      - REDIS_CACHE_URL=${REDIS_CACHE_URL}

      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - SPRING_LIQUIBASE_ENABLED=true

      - EUREKA_URL_DEFAULT=${EUREKA_URL_DEFAULT}
    depends_on:
      - order-postgres
      - discovery-service
    networks:
      - order-network
    volumes:
      - .env:/app/.env

networks:
  company-network:
  order-network:
  monitoring-network:
  gateway-network:

volumes:
  company_postgres_data:
  order_postgres_data:
  kong_postgres_data: