global:
  scrape_interval: 30s

scrape_configs:
  - job_name: 'company-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          application: "company-api-dev"